# Generated by Django 3.0 on 2019-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenCVRestApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
