# Generated by Django 3.0 on 2019-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenCVRestApi', '0002_imagecv'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecv',
            name='base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
