# Generated by Django 3.0 on 2019-12-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenCVRestApi', '0003_imagecv_base64'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
